import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { GraphQLClient, gql } from "graphql-request";
import BlogCard from "../components/BlogCard";

//インスタンス化
const graphcms = new GraphQLClient(
  "https://api-ap-northeast-1.hygraph.com/v2/clbyfz6um0d5701urfx8031n8/master"
);

//hygraphで作成し、指定したオブジェクトをAPI経由で取得
const QUERY = gql`
  {
    posts {
      id
      title
      datePublished
      slug
      content {
        html
      }
      author {
        name
        avatar {
          url
        }
      }
      photo {
        createdBy {
          id
        }
        url
      }
    }
  }
`;

//SSGを使う上での固定関数
//通常リターンはファンクションに返すが、この固定のものはpropsオブジェクトのものとなる
export async function getStaticProps() {
  const { posts } = await graphcms.request(QUERY);
  return {
    props: {
      posts,
    },
  };
}

export default function Home({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.title}>
          <h2>Next.jsとGraphQlブログ</h2>
        </div>
        <div className={styles.gridWrapper}>
          {posts.map((post) => {
            return (
              <BlogCard
                photo={post.photo}
                title={post.title}
                author={post.author}
                date={post.datePublished}
                slug={post.slug}
                key={post.id}
              />
            );
          })}
        </div>
      </main>
    </div>
  );
}
